eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  main:
    web-application-type: REACTIVE
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: authentication
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/authentication/**
        - id: billing
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/billing/**
        - id: notification
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/notification/**
        - id: payment
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/payment/**
        - id: service
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/service/**
